// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4remIrEwAp6iri5_uKQHmumgCsNoJJ8I',
    appId: '1:656596007531:web:0460358bb0a3897c168f2e',
    messagingSenderId: '656596007531',
    projectId: 'bkk-svelte',
    authDomain: 'bkk-svelte.firebaseapp.com',
    storageBucket: 'bkk-svelte.appspot.com',
    measurementId: 'G-LV290MDXS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgtdRRsB31mQycTiaZAzb7tvOPlDhTyMA',
    appId: '1:656596007531:android:c04836b25c7307f7168f2e',
    messagingSenderId: '656596007531',
    projectId: 'bkk-svelte',
    storageBucket: 'bkk-svelte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbcN5kZd4HwhBLWwB3VPtJwhXgobItbfY',
    appId: '1:656596007531:ios:d68e344bf55c3ec4168f2e',
    messagingSenderId: '656596007531',
    projectId: 'bkk-svelte',
    storageBucket: 'bkk-svelte.appspot.com',
    iosClientId: '656596007531-6vegogqbqvokj3uukpj3vvsaos8lra4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.bartalfutarFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbcN5kZd4HwhBLWwB3VPtJwhXgobItbfY',
    appId: '1:656596007531:ios:fdfab2e744e3b7da168f2e',
    messagingSenderId: '656596007531',
    projectId: 'bkk-svelte',
    storageBucket: 'bkk-svelte.appspot.com',
    iosClientId: '656596007531-ff4kqttn5ppt7cdmtcm2cntlbm75nqnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bartalfutarFlutter.RunnerTests',
  );
}
